version: '3'

services:
  kafka:
    image: "bitnami/kafka:3.4.0"
    container_name: hcf-kafka
    restart: unless-stopped
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=DOCKER_INTERNAL
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,PLAINTEXT://:9092,DOCKER_INTERNAL://:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER_INTERNAL:PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,DOCKER_INTERNAL://kafka:19092
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=wunIH31zRY2LvJKHyrKoVQ
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - hcf-net
    volumes:
      - "kafka_data:/bitnami"

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: hcf-schema-registry
    restart: unless-stopped
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:19092
    ports:
      - "8081:8081"
    networks:
      - hcf-net
    depends_on:
      - kafka

  conduktor-platform:
    image: conduktor/conduktor-platform:latest
    container_name: hcf-conduktor-platform
    restart: unless-stopped
    environment:
      CDK_ORGANIZATION_NAME: "demo"
      CDK_ADMIN_EMAIL: "admin@admin.io"
      CDK_ADMIN_PASSWORD: "admin"
      CDK_CLUSTERS_0_ID: "default"
      CDK_CLUSTERS_0_NAME: "My Kafka Cluster"
      CDK_CLUSTERS_0_COLOR: "#0013E7"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "DOCKER_INTERNAL://kafka:19092"
      CDK_CLUSTERS_0_SCHEMAREGISTRY_URL: "http://schema-registry:8081"
    ports:
      - "8080:8080"
    networks:
      - hcf-net
    volumes:
      - conduktor_data:/var/conduktor
    depends_on:
      - kafka
      - schema-registry

  postgres:
    image: bitnami/postgresql:14.1.0-debian-10-r31
    container_name: hcf-postgres
    restart: unless-stopped
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - 5432:5432
    networks:
      - hcf-net
    volumes:
      - postgres:/bitnami/postgresql

volumes:
  conduktor_data:
  kafka_data:
  postgres:

networks:
  hcf-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
          gateway: 10.20.30.1
